AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template launches an EC2 instance which enables SSH.

Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08e4e35cccc6189f4
      InstanceType: t2.micro
      KeyName: firstkey # Please use your own key name without .pem
      SecurityGroups: 
        - aa.first
      Tags:
        - Key: Name
          Value: zehra
      UserData:
        Fn::Base64: |
          #!/bin/bash

          #update os
          yum update -y
          #install apache server
          yum install -y httpd
          yum install -y wget
          chmod -R 777 /var/www/html
          cd /var/www/html
          wget https://raw.githubusercontent.com/ycetin94/2.poject/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/ycetin94/2.poject/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/ycetin94/2.poject/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/ycetin94/2.poject/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/ycetin94/2.poject/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.jpg
          # start apache server
          systemctl start httpd
          systemctl enable httpd